$HTML =`
 ConvertTo-HTML -Body " $topHeader $sideNavigation $BiosInfo $ProcessorInfo $RAMInfo $OSinfo`
  $PSversion $diskArray $NetAdapterInfo $hostsInfo $searchScripts $ServicesInfo $AppInfo $sortTables $topButton"`
 -Head $header -Title "Computer Information Report"`
 -PostContent "<p id='Footer'>Report generated by $env:USERNAME at $footerDate   |   Public IP Address: $publicIP</p>"
#! ************************************** BUILD HTML ***************************************
#$Title $bootInfo $sideNavigation $topHeader